/**
 * Simple TestCafe test example
 * Generated by TestCafe MCP Server
 */

import { Selector } from 'testcafe';

fixture('Simple Login Test')
  .page('https://example.com/login');

test('User can login successfully', async t => {
  // Navigate to login page
  await t.navigateTo('https://example.com/login');
  
  // Fill in login form
  await t.typeText(Selector('#username'), 'testuser');
  await t.typeText(Selector('#password'), 'password123');
  
  // Submit form
  await t.click(Selector('#login-button'));
  
  // Verify successful login
  await t.expect(Selector('.welcome-message').exists).ok('Welcome message should appear');
  await t.expect(Selector('.user-profile').visible).ok('User profile should be visible');
});

test('Login form validation works', async t => {
  // Try to submit empty form
  await t.click(Selector('#login-button'));
  
  // Check for validation errors
  await t.expect(Selector('.error-message').exists).ok('Error message should appear');
  await t.expect(Selector('.error-message').textContent).contains('Username is required');
});